desc "Runs all the tests"
lane :test do
  scan(
    project: "mixtour.xcodeproj",
    scheme: "mixtour-en",
    testplan: "AllTests"
  )
end

desc "Uploads to TestFlight and notifies users"
lane :upload do
  increment_build_number(
    build_number: "#{ENV['BITRISE_BUILD_NUMBER']}"
  )

  gym(
    scheme: "mixtour-en",
    configuration: "Release",
    clean: true,
  )
  
  new_commits = changelog_from_git_commits(
    tag_match_pattern: "*"
  )

  pilot(
    changelog: new_commits
  )
end
