desc "Runs all the tests"
lane :test do
  scan(
    project: "mixtour.xcodeproj",
    scheme: "mixtour-en",
    testplan: "AllTests"
  )
end

desc "Uploads to TestFlight and notifies users"
lane :upload do
  gym(
    scheme: "mixtour-en",
    configuration: "Release",
    clean: true,
  )
  
  new_commits = changelog_from_git_commits(
    tag_match_pattern: "*"
  )

  UI.message("build number: #{ENV['BITRISE_BUILD_NUMBER']}")

  pilot(
    build_number: "2",
    changelog: new_commits
  )
end
